name: hello

on: push

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: hello
        run: |
          cd /home/runner
          python3 src/hello.py
